### ISSUE TITLE
Set up S4 signup to accept Bitcoin for S4 subscriptions (already supported by Stripe)

### ISSUE THREAD

**Issue by Liz315** [LeastAuthority/leastauthority.com#459] opened 2016-12-22 15:15 UTC
Stripe allows for Bitcoin payments, so we could easily enable this feature to accept Bitcoin payments for the S4 service: https://stripe.com/docs/bitcoin

**Comment by exarkun** [comment] 2016-12-25 23:18
It looks like Stripe doesn't support subscriptions paid via Bitcoin.  We can probably implement the necessary recurring-billing logic on our end but that does make it more work than just a quick change to our Stripe-using JavaScript (as one might have hoped would be sufficient).

**Comment by exarkun** [comment] 2017-01-19 15:36
Duplicate of #302

**Closed by exarkun** 2017-01-19 15:36 UTC
