### ISSUE TITLE
Persistent performance issues with wormhole server

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/leastauthority.com#539] opened 2017-05-22 23:58 UTC
As mentioned previously in Slack, I've come across some persisting performance issues with the Least Authority wormhole server that result in transfers taking a good ~10 seconds longer than expected (which, compared to the duration of the other steps in a typical Gridsync setup run, is long enough to lead users to think that something is 'stuck' -- and which, more broadly, contributes to bad UX that we should arguably strive to avoid).

To demonstrate that this is an issue specific to our deployment (and not to wormhole servers in general), I ran a simple test, piping a 60 kB JSON blob into `wormhole send` across three different servers using the following command:

`cat settings.json | wormhole --relay-url $SERVER send --text -`

...where `$SERVER` was one of the following relay URLs:

```
ws://relay.magic-wormhole.io:4000/v1
ws://wormhole.gridsync.io:4000/v1
ws://wormhole.leastauthority.com:4000/v1
```

Running `time wormhole --relay-url $SERVER receive $CODE` five times for each server (and rotating to the next server between runs so as to lessen the effects of any potential lag-spikes with my ISP) gave me the following results:

```
wormhole --relay-url ws://relay.magic-wormhole.io:4000/v1 receive   1.19s user 0.16s system 48% cpu 2.798 total
wormhole --relay-url ws://relay.magic-wormhole.io:4000/v1 receive   1.14s user 0.15s system 48% cpu 2.618 total
wormhole --relay-url ws://relay.magic-wormhole.io:4000/v1 receive   1.13s user 0.14s system 49% cpu 2.550 total
wormhole --relay-url ws://relay.magic-wormhole.io:4000/v1 receive   1.17s user 0.15s system 48% cpu 2.740 total
wormhole --relay-url ws://relay.magic-wormhole.io:4000/v1 receive   1.16s user 0.12s system 46% cpu 2.764 total

wormhole --relay-url ws://wormhole.gridsync.io:4000/v1 receive   1.15s user 0.13s system 61% cpu 2.099 total
wormhole --relay-url ws://wormhole.gridsync.io:4000/v1 receive   1.17s user 0.15s system 62% cpu 2.122 total
wormhole --relay-url ws://wormhole.gridsync.io:4000/v1 receive   1.16s user 0.12s system 60% cpu 2.117 total
wormhole --relay-url ws://wormhole.gridsync.io:4000/v1 receive   1.21s user 0.15s system 48% cpu 2.792 total
wormhole --relay-url ws://wormhole.gridsync.io:4000/v1 receive   1.13s user 0.15s system 59% cpu 2.161 total

wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.20s user 0.15s system 10% cpu 13.408 total
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.13s user 0.13s system 7% cpu 16.604 total
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.20s user 0.15s system 9% cpu 14.010 total
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.17s user 0.15s system 10% cpu 13.071 total
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.20s user 0.14s system 9% cpu 13.700 total
```

Interestingly, if I send only a few bytes across the wire, the results are much more reasonable; `echo 'hi' | wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 send --text -` resulted in the following `wormhole receive` times:

```
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.07s user 0.14s system 42% cpu 2.864 total
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.04s user 0.16s system 36% cpu 3.262 total
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.07s user 0.14s system 40% cpu 2.986 total
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.10s user 0.15s system 42% cpu 2.962 total
wormhole --relay-url ws://wormhole.leastauthority.com:4000/v1 receive   1.09s user 0.14s system 40% cpu 2.997 total
```

It might be worth reiterating here that my client and both non-Least Authority servers were running magic-wormhole version 0.9.2, while the Least Authority server -- which runs 0.9.2 according to @exarkun -- is displaying a version mismatch warning during negotiation (`Server claims 0+unknown is current, but ours is 0.9.2`). Could this be related at all to the issue? Can the Least Authority server be redeployed with a proper version string so as to eliminate this as a variable?

**Comment by exarkun** [comment] 2017-06-23 13:43
I can confirm this is (still) the behavior:

{"data-size": 64, "relay-url": "ws://relay.magic-wormhole.io:4000/v1", "average-transfer-seconds": 1.0699007511138916}
{"data-size": 1024, "relay-url": "ws://relay.magic-wormhole.io:4000/v1", "average-transfer-seconds": 1.089825439453125}
{"data-size": 65536, "relay-url": "ws://relay.magic-wormhole.io:4000/v1", "average-transfer-seconds": 2.0235766887664797}
{"data-size": 64, "relay-url": "ws://wormhole.gridsync.io:4000/v1", "average-transfer-seconds": 0.700524377822876}
{"data-size": 1024, "relay-url": "ws://wormhole.gridsync.io:4000/v1", "average-transfer-seconds": 0.6899430274963378}
{"data-size": 65536, "relay-url": "ws://wormhole.gridsync.io:4000/v1", "average-transfer-seconds": 1.9661959648132323}
{"data-size": 64, "relay-url": "ws://wormhole.leastauthority.com:4000/v1", "average-transfer-seconds": 3.282702589035034}
{"data-size": 1024, "relay-url": "ws://wormhole.leastauthority.com:4000/v1", "average-transfer-seconds": 3.3022177696228026}
{"data-size": 65536, "relay-url": "ws://wormhole.leastauthority.com:4000/v1", "average-transfer-seconds": 10.901998376846313}

**Comment by exarkun** [comment] 2017-06-23 13:56
A refinement of the benchmark shows the time is not being spent allocating a wormhole code for the transfer:

```
{"data-size": 64, "relay-url": "ws://relay.magic-wormhole.io:4000/v1", "average-transfer-seconds": {"time-to-receive": 1.0821204662322998, "time-to-code": 0.330903434753418}}
{"data-size": 1024, "relay-url": "ws://relay.magic-wormhole.io:4000/v1", "average-transfer-seconds": {"time-to-receive": 1.0679587841033935, "time-to-code": 0.30382699966430665}}
{"data-size": 65536, "relay-url": "ws://relay.magic-wormhole.io:4000/v1", "average-transfer-seconds": {"time-to-receive": 1.9357872486114502, "time-to-code": 0.30171980857849123}}
{"data-size": 64, "relay-url": "ws://wormhole.gridsync.io:4000/v1", "average-transfer-seconds": {"time-to-receive": 0.8789855480194092, "time-to-code": 0.23374676704406738}}
{"data-size": 1024, "relay-url": "ws://wormhole.gridsync.io:4000/v1", "average-transfer-seconds": {"time-to-receive": 0.6532424449920654, "time-to-code": 0.17865405082702637}}
{"data-size": 65536, "relay-url": "ws://wormhole.gridsync.io:4000/v1", "average-transfer-seconds": {"time-to-receive": 1.3774561882019043, "time-to-code": 0.18387870788574218}}
{"data-size": 64, "relay-url": "ws://wormhole.leastauthority.com:4000/v1", "average-transfer-seconds": {"time-to-receive": 2.932756805419922, "time-to-code": 0.7682481288909913}}
{"data-size": 1024, "relay-url": "ws://wormhole.leastauthority.com:4000/v1", "average-transfer-seconds": {"time-to-receive": 3.0316298484802244, "time-to-code": 0.7914966106414795}}
{"data-size": 65536, "relay-url": "ws://wormhole.leastauthority.com:4000/v1", "average-transfer-seconds": {"time-to-receive": 11.484837818145753, "time-to-code": 0.7718661785125732}}
```

This is consistent with the observation that the amount of data to be transferred affects the total time (the code is allocated before any data is transferred).

**Comment by exarkun** [comment] 2017-06-23 13:57
I'm not sure if it is significant but I also observe that wormhole.leastauthority.com has the greatest latency of the three servers for both measurements.

**Comment by exarkun** [comment] 2017-06-23 14:27
There doesn't seem to be any particular data size where it falls off a cliff.  It's just (eyeball) linearly slower as data size goes up.

**Comment by exarkun** [comment] 2017-06-27 19:31
Measuring round-trip-time to see messages added to the mailbox get echo'd back, it looks like there's just a ton of latency on the connection.  Moreover, this latency goes away when connecting directly to the Node IP - bypassing the ELB that makes the server publicly visible (this can only be done from inside the Kubernetes cluster, of course).

Also noteworthy is that the staging deployment of the wormhole server (on a different AWS account but otherwise the same) does not exhibit this latency even when used via its ELB.

**Comment by exarkun** [comment] 2017-07-07 18:02
On prompting from @meejah I investigated a CPU bottleneck as the problem.  I raised the CPU limit for the wormhole server from 10m to 1000m (1% of a CPU to 100% of a CPU) and the time-to-receive value fell to under 2 seconds.

I can't explain why I didn't observe the same problem with the staging wormhole earlier but I _do_ observe the problem now and it is also alleviated by twiddling the CPU limits.

Getting accepted performance for a single user seems to require about 25% of a CPU.  This seems really, really high to me.  I don't want to give the wormhole server much more than this because it significantly cuts into the number of actual customer deployments we can run.  This will become less significant in the long term (using up 50% or 100% of one CPU after we have 50 nodes won't matter so much - but right now we have 2 nodes).  However, it seems like vastly too much CPU time to be spending to transfer 64KiB of data.  We should probably look into profiling and optimizing magic-wormhole before too long.

For now, we've taken the icon data out of the magic-wormhole transfer and I've raised the CPU limit slightly.  Combined, this means the wormhole phase of signup proceeds at an acceptable pace.

**Closed by exarkun** 2017-07-07 18:02 UTC

**Comment by meejah** [comment] 2017-07-07 18:28
FWIW, this *may* be an underlying Autobahn problem -- re-building a single 64KiB message (and doing XOR over it) shouldn't be too hard, but perhaps it is?

**Comment by meejah** [comment] 2017-07-07 18:29
There was a problem reported in Autobahn where a user was sending *massive* single messages (way more than 65KiB) and occasionally experiencing some truncated data in the middle. This could have been a javascript (not python) problem though.
